const {test}=require('node:test');
const assert=require('node:assert/strict');
const path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const {pgcrypto}=require('@electric-sql/pglite/contrib/pgcrypto');
process.env.JWT_SECRET='reports-contract-test-secret';
test('passenger report HTTP contract, ownership, references and retry deduplication',async t=>{
 const pg=new PGlite({extensions:{pgcrypto}});t.after(()=>pg.close());
 const execute=async(sql,args)=>args?pg.query(sql,args):(await pg.exec(sql)).at(-1);
 await require('../scripts/migration-runner').migrate({query:execute},path.join(__dirname,'../src/db/migrations'),()=>{});
 require('../dist/db').query=execute;require('../dist/redis/cache').incrementRateLimit=async()=>1;
 const user=(await execute("INSERT INTO users(auth_provider) VALUES('guest') RETURNING id")).rows[0];
 const route=(await execute("INSERT INTO routes(name,short_name,visible_in_app) VALUES('Reports','R',true) RETURNING id")).rows[0];
 const variant=(await execute("INSERT INTO route_variants(route_id,name,direction,coordinates) VALUES($1,'Ida','ida','[[0,0],[1,1]]') RETURNING id",[route.id])).rows[0];
 const stop=(await execute("INSERT INTO stops(route_id,variant_id,name,latitude,longitude,sequence) VALUES($1,$2,'Stop',0,0,0) RETURNING id",[route.id,variant.id])).rows[0];
 const express=require('express'),jwt=require('jsonwebtoken');const app=express();app.use(express.json());app.use('/reports',require('../dist/reports/reports.routes').reportsRouter);app.use(require('../dist/shared/errors').errorHandler);
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));
 const base='http://127.0.0.1:'+server.address().port;
 const token=jwt.sign({sub:user.id,role:'user'},process.env.JWT_SECRET);
 const post=async body=>{const r=await fetch(base+'/reports',{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};};
 const body={type:'stopIssue',severity:'high',stop_id:stop.id,message:'Parada bloqueada',client_id:'retry-1'};
 const first=await post(body);assert.equal(first.status,201,JSON.stringify(first.data));assert.equal(first.data.report.stop_id,stop.id);assert.equal(first.data.report.route_id,route.id);assert.equal(first.data.report.severity,'high');
 const retry=await post(body);assert.equal(retry.status,200);assert.equal(retry.data.report.id,first.data.report.id);
 assert.equal((await post({...body,message:'Different'})).status,409);
 for(const type of ['delay','crowded','detour','breakdown','other'])assert.equal((await post({...body,type,client_id:type})).status,201);
 const legacy=await post({...body,type:'Ruta desviada',severity:'Leve',client_id:'legacy'});assert.equal(legacy.data.report.type,'detour');assert.equal(legacy.data.report.severity,'low');
 for(const patch of [{type:'invalid'},{severity:'critical'},{message:'x'.repeat(2001)},{latitude:1},{longitude:200},{route_id:'00000000-0000-0000-0000-000000000001'}])assert.equal((await post({...body,...patch,client_id:'bad'})).status,400);
 const history=await fetch(base+'/reports/my',{headers:{authorization:'Bearer '+token}});assert.equal((await history.json()).reports.length,7);
 assert.equal((await fetch(base+'/reports/my')).status,401);
});
